import random


class songListGenerator:
    def __init__(self, mood) -> None:
        self.selected_mood = mood

    def generate_list(self):
        if self.selected_mood == "Happy":
            complete_list = [
                "Jai Ho",
                "Balam Pichkari",
                "Ainvayi Ainvayi",
                "London Thumakda",
                "Morni Banke",
                "Badtameez Dil",
                "Gallan Goodiyaan",
                "Ae Mere Humsafar",
                "Radha",
                "Dil Chahta Hai",
                "Navrai Majhi",
                "Nachde Ne Saare",
                "Dance Pe Chance",
                "Gal Mitthi Mitthi Bol",
                "Genda Phool",
                "Kar Gayi Chull",
                "Saudagar Sauda Kar",
                "Tum Hi Ho Bandhu",
                "Bole Chudiyan",
                "Happy",
                "Can't Stop the Feeling!",
                "Uptown Funk",
                "Walking on Sunshine",
                "Good Vibrations",
                "Don't Stop Believin'",
                "Shake It Off",
                "I Gotta Feeling",
                "Dancing Queen",
                "I Will Survive",
                "Happy Together",
                "Best Day of My Life",
                "Twist and Shout",
                "All Star",
                "Here Comes the Sun",
                "Walking on Sunshine",
                "Sweet Caroline",
                "Dil Dhadakne Do",
                "Bom Diggy Diggy",
                "Sadi Gali",
                "Lakdi Ki Kaathi",
                "The Bare Necessities",
                "Brown Munde",
                "Jashn-e-Ishqa",
                "Tera Hero Idhar Hai",
                "Daru Desi",
                "Tareefan",
                "Move Your Lakk",
                "Aankh Marey",
                "Ghungroo",
                "Tamma Tamma"
            ]
            list = random.sample(complete_list, 30)
            return list

        elif self.selected_mood == "Sad":
            complete_list = [
                "Tadap Tadap - Hum Dil De Chuke Sanam",
                "Tum Hi Ho - Aashiqui 2",
                "Agar Tum Saath Ho - Tamasha",
                "Kya Hua Tera Wada - Hum Kisise Kum Naheen",
                "Jeene Laga Hoon - Ramaiya Vastavaiya",
                "Tujhe Bhula Diya - Anjaana Anjaani",
                "Channa Mereya - Ae Dil Hai Mushkil",
                "Do Lafzon Ki Hai Dil Ki Kahani - The Great Gambler",
                "Ae Zindagi Gale Laga Le - Sadma",
                "Jiye To Jiye Kaise - Saajan",
                "Kal Ho Naa Ho - Kal Ho Naa Ho",
                "Tujh Mein Rab Dikhta Hai - Rab Ne Bana Di Jodi",
                "Chupke Se - Saathiya",
                "Yeh Dooriyan - Love Aaj Kal",
                "Kabira - Yeh Jawaani Hai Deewani",
                "Tere Bina - Guru",
                "Kyun Na Hum Tum - Barfi!",
                "Hasi Ban Gaye - Hamari Adhuri Kahani",
                "Bekhayali - Kabir Singh",
                "Tum Se Hi - Jab We Met",
                "Maiyya Yashoda - Hum Saath-Saath Hain",
                "Agar Tum Mil Jao - Zeher",
                "Mitti Di Khushboo - Mitti Di Khushboo",
                "Dekh Lena - Tum Bin 2",
                "Sun Saathiya - ABCD 2",
                "Dil De Diya Hai - Masti",
                "Pee Loon - Once Upon A Time In Mumbaai",
                "O Saathi - Baaghi 2",
                "Ae Mere Humsafar - Qayamat Se Qayamat Tak",
                "Humein Tumse Pyar Kitna - Kudrat",
                "Lag Jaa Gale - Woh Kaun Thi",
                "Bhula Dena - Aashiqui 2",
                "Ya Rabba - Salaam-E-Ishq",
                "Aye Khuda - Murder 2",
                "Kaisi Hai Ye Rut - Dil Chahta Hai",
                "Woh Lamhe Woh Baatein - Zeher",
                "Aankhon Mein Teri - Om Shanti Om",
                "Ae Watan - Raazi",
                "Suno Na - Jhankaar Beats",
                "O Re Piya - Aaja Nachle",
                "Aaj Din Chadheya - Love Aaj Kal",
                "Zara Si - Jannat",
                "Mujh Mein Tu - Special 26",
                "Aye Mere Humsafar - Baazigar",
                "Kaise Mujhe - Ghajini",
                "Kahin To Hogi Woh - Jaane Tu Ya Jaane Na",
                "Aadat - Kalyug",
                "Mera Mann - Mann",
                "Jaane Nahin Denge Tujhe - 3 Idiots",
                "Bolna - Kapoor & Sons"
            ]
            list = random.sample(complete_list, 30)
            return list

        elif self.selected_mood == "Devotional":
            complete_list = [
                "Shree Ganeshay Dheemahi",
                "Shree Hanuman Chalisa",
                "Ram Siya Ram",
                "Shiv Tandav Stotram",
                "Madhurashtakam",
                "Sukhkarta Dukhharta",
                "Aarti Kunj Bihari Ki",
                "Shree Hari Stotram",
                "Yamunashtakam",
                "Kabhi Ram Banke Kabhi Shyam Banke",
                "Kaun Kehte Hai Bhagwan Aate Nahi",
                "Mann Mohanaa",
                "Savaiyaa Raadhey Krishn Ki Jyoti",
                "O Paalanhaare",
                "Teri Hai Zameen Tera Aasman",
                "Ek Tu Hi Bharosa",
                "Kun Faya Kun",
                "Bhar Do Jholi Meri",
                "Yashomati Maiya Se Bole Nandlala",
                "Satyam Shivam Sundaram",
                "Itni Shakti Hamein Dena Data",
                "Ae Malik Tere Bande Hum",
                "Man Basia",
                "Raghupati Raghav Raja Ram",
                "Hare Krishna Hare Rama",
                "Shri Ram Jaanki Baithe Hai",
                "Meri Maa Ke Barabar Koi Nahi",
                "Shree Krishna Govind Hare Murari",
                "Shish Nawata Hoon",
                "Mere Ghar Ram Aaye Hain",
                "Mere Kanha",
                "Om Jai Jagdish Hare",
                "Mere Baba",
                "Ganesha",
                "Main Balak Tu Mata",
                "Kabira",
                "Meri Mai",
                "Mere Bhole Nath",
                "Maai Hai Na",
                "Siya Ram",
                "Mere Kanha Bhool Na Jaana",
                "Morya Re Bappa",
                "Mast Kalandar",
                "Shirdi Wale Sai Baba",
                "Khwaja Mere Khwaja",
                "Noor E Khuda",
                "Tajdar-E-Haram",
                "Arziyan",
                "Aaya Tere Dar Par",
                "Hasbi Rabbi",
                "Allah Hi Reham",
                "Maula Mere Lele Meri Jaan",
                "Piya Haji Ali",
                "Wohi Khuda",
                "Karayaanum Parayaanum",
                "Nithya Snehathal",
                "Krusin Kandu Njan",
                "Ente Mukhan",
                "Ella Snehathinum",
                "Kandaalo Aalariyukilla",
                "Deva",
                "Gajanana",
                "Jai Dev Jai Dev Jai Mangal Murti",
                "Aarti Shree Gayatri Shree",
                "Aarti Shree Ambaji",
                "Kaamnapurti Stotra",
                "Aarti Shree Lakshmiji",
                "Ganpati Chalisa",
                "Om Namah Sivay",
                "Ruso Na Sai",
                "Sai Rehem Nazar Karna",
                "Mere Sai",
                "Bhddhang Saranang Gachhami",
                "Radhe Mohan",
                "Om Namoji Aadya",
                "Tum Hi Devta Ho",
                "Shiv Aarti",
                "Maha Mrityunjaya Mantra",
                "Chalo Bulawa Aaya Hai",
                "Jai Mata Di",
                "Pyara Saja Hai Tera Dwar",
                "Lal Chuda Lal Bindi",
                "Shree Durga Chalisa",
                "Jay Ambe Gauri",
                "Jai Jai Tulsi Mata",
                "Maiya Ka Darbar",
                "Sada Suhagan Mata Tu Hai",
                "Durga Amritwani",
                "Ganga Aarti",
                "Ramayan Chaupai",
                "Mere Banke Bihari Lal",
                "Hare Rama Hare Rama Rama Ram",
                "Mithe Ras Se Bharyo Re",
                "Aisi Laagi Lagan Meera Ho Gayi Magan",
                "Jai Jai Radha Raman Hari Bol",
                "Krishna Teri Hi Gyi",
                "O Govinda",
                "Nandlala",
                "O Radhe"
            ]
            list = random.sample(complete_list, 30)
            return list

        elif self.selected_mood == "Relaxing":
            complete_list = [
                "Tum Mile - Tum Mile",
                "Tum Jo Aaye - Once Upon A Time In Mumbaai",
                "Tera Ban Jaunga - Kabir Singh",
                "Tum Se Hi - Jab We Met",
                "Tum Mile (Reprise) - Tum Mile",
                "Rehna Tu - Delhi-6",
                "Pee Loon - Once Upon A Time In Mumbaai",
                "Rozana - Naam Shabana",
                "Kho Gaye Hum Kahan - Baar Baar Dekho",
                "Kaise Mujhe/Tum Ho - T-Series Mixtape",
                "Chasing Cars - Snow Patrol",
                "All of Me - John Legend",
                "Hallelujah - Jeff Buckley",
                "Someone Like You - Adele",
                "Lost Stars - Adam Levine",
                "Breathe Me - Sia",
                "A Thousand Years - Christina Perri",
                "To Build a Home - The Cinematic Orchestra",
                "Skinny Love - Bon Iver",
                "Fix You - Coldplay",
                "Pure Shores - All Saints",
                "Say Something - A Great Big World & Christina Aguilera",
                "Dreams - Fleetwood Mac",
                "Your Song - Elton John",
                "Make You Feel My Love - Adele",
                "Landslide - Fleetwood Mac",
                "Angie - The Rolling Stones",
                "Yellow - Coldplay",
                "Teardrop - Massive Attack",
                "Wish You Were Here - Pink Floyd",
                "Fast Car - Tracy Chapman",
                "Vincent - Don McLean",
                "Sittin' On The Dock of The Bay - Otis Redding",
                "Time After Time - Cyndi Lauper",
                "Imagine - John Lennon",
                "The Sound of Silence - Simon & Garfunkel",
                "Stand By Me - Ben E. King",
                "Yesterday - The Beatles",
                "Don't Know Why - Norah Jones",
                "Budapest - George Ezra",
                "Lover, You Should've Come Over - Jeff Buckley",
                "Songbird - Fleetwood Mac",
                "Horse with No Name - America",
                "All I Want - Kodaline",
                "Blackbird - The Beatles",
                "Three Little Birds - Bob Marley & The Wailers",
                "Close to You - The Carpenters",
                "Dock of the Bay - Otis Redding",
                "Breathe - Télépopmusik",
                "Heartbeats - José González"
            ]
            list = random.sample(complete_list, 30)
            return list

        elif self.selected_mood == "Romantic":
            complete_list = [
                "Tum Hi Ho",
                "Tum Mile",
                "Tum Jo Aaye",
                "Janam Janam",
                "Raabta",
                "Tera Hone Laga Hoon",
                "Jeene Laga Hoon",
                "Tum Se Hi",
                "Pee Loon",
                "Janib",
                "Hasi Ban Gaye",
                "Tera Ban Jaunga",
                "Sun Saathiya",
                "Samjhawan",
                "Bolna",
                "Can't Help Falling in Love",
                "All of Me",
                "Thinking Out Loud",
                "Unchained Melody",
                "I Will Always Love You",
                "A Thousand Years",
                "Wonderful Tonight",
                "Endless Love",
                "My Heart Will Go On",
                "Everything I Do (I Do It For You)",
                "When You Say Nothing at All",
                "L-O-V-E",
                "Make You Feel My Love",
                "The Way You Look Tonight",
                "Amazed",
                "Your Song",
                "I Don't Want to Miss a Thing",
                "I Just Called to Say I Love You",
                "At Last",
                "Eternal Flame",
                "Just the Way You Are",
                "Stand by Me",
                "A Whole New World",
                "Wonderful World",
                "Iris",
                "Truly Madly Deeply",
                "Un-break My Heart",
                "From This Moment On",
                "Hero",
                "Nothing's Gonna Change My Love for You",
                "Close to You",
                "Kiss Me",
                "Have I Told You Lately",
                "Can't Take My Eyes Off You",
                "Love Me Tender",
                "Everything",
                "Iris",
                "The Power of Love",
                "Make You Feel My Love",
                "As Long As You Love Me",
                "Say Something",
                "Can't Help Falling in Love",
                "Chasing Cars",
                "The First Time Ever I Saw Your Face",
                "Thank You",
                "I Want to Know What Love Is",
                "Close to You",
                "All Out of Love",
                "(Everything I Do) I Do It for You",
                "Can't Smile Without You",
                "Woman in Love",
                "I'll Be There for You",
                "Baby Can I Hold You",
                "I'll Stand by You",
                "Love Me Like You Do"
            ]
            list = random.sample(complete_list, 30)
            return list

        elif self.selected_mood == "Nostalgic":
            complete_list = {}
            list = random.sample(complete_list, 30)
            return list

        elif self.selected_mood == "Celebration":
            complete_list = [
                "Mera Naam Chin Chin Chu",
                "Badtameez Dil",
                "London Thumakda",
                "Navrai Majhi",
                "Gallan Goodiyaan",
                "Celebration",
                "We Will Rock You",
                "Uptown Funk",
                "Happy",
                "Dancing Queen",
                "Don't Stop Believin'",
                "Dancing in the Street",
                "Can't Stop the Feeling!",
                "All Night Long (All Night)",
                "Footloose",
                "Saturday Night's Alright (For Fighting)",
                "Party in the U.S.A.",
                "Waka Waka (This Time for Africa)",
                "Twist and Shout",
                "Shut Up and Dance",
                "Conga",
                "Fireball",
                "Wannabe",
                "Raise Your Glass",
                "Walking on Sunshine",
                "Dance Monkey",
                "I Gotta Feeling",
                "Get the Party Started",
                "Firework",
                "Can't Stop the Music",
                "Y.M.C.A.",
                "Hey Ya!",
                "Livin' la Vida Loca",
                "Hips Don't Lie",
                "Cha Cha Slide",
                "Macarena",
                "Sweet Caroline",
                "Hey Jude",
                "Crazy Little Thing Called Love",
                "Livin' on a Prayer",
                "Celebration",
                "Shake It Off",
                "Hey Brother",
                "September",
                "I Wanna Dance with Somebody",
                "Uptown Girl",
                "Wannabe",
                "Can't Stop the Feeling!",
                "Dynamite",
                "Twist and Shout",
                "Ainvayi Ainvayi",
                "Gulabo",
                "Nachde Ne Saare",
                "London Thumakda",
                "Badri Ki Dulhania",
                "Dil Dhadakne Do",
                "Gallan Goodiyaan",
                "Proper Patola",
                "Tunak Tunak Tun",
                "Ghagra",
                "Dance Basanti",
                "Chammak Challo",
                "Malhari",
                "Hookah Bar",
                "Kala Chashma",
                "I Gotta Feeling",
                "Don't Stop the Party",
                "Firework",
                "Happy",
                "Shut Up and Dance"
            ]
            list = random.sample(complete_list, 30)
            return list

        elif self.selected_mood == "Energetic":
            complete_list = [
                "London Thumakda",
                "Ainvayi Ainvayi",
                "Balam Pichkari",
                "Kamariya",
                "Badtameez Dil",
                "Mauja Hi Mauja",
                "Nashe Si Chadh Gayi",
                "Tareefan",
                "Gulaabo",
                "Aankh Marey",
                "Malhari",
                "Ghungroo",
                "Radha",
                "Sweety Tera Drama",
                "Bom Diggy Diggy",
                "Tamma Tamma Again",
                "Laila Main Laila",
                "Kala Chashma",
                "The Jawaani Song",
                "Ding Dang",
                "Kar Gayi Chull",
                "High Rated Gabru",
                "Proper Patola",
                "Badri Ki Dulhania",
                "Dil Chori",
                "Chalti Hai Kya 9 Se 12",
                "Disco Disco",
                "Aao Kabhi Haveli Pe",
                "Breakup Song",
                "Banno",
                "Garmi",
                "Saturday Saturday",
                "Swag Se Swagat",
                "Morni Banke",
                "Radhe Radhe",
                "Baby Ko Bass Pasand Hai",
                "Cutiepie",
                "Kamariya (Stree)",
                "Sweety Slowly Slowly",
                "Morni Banke (Badhaai Ho)",
                "Coca Cola (Luka Chuppi)",
                "Mummy Kasam (Nawabzaade)",
                "Speaker Phat Jaaye (Total Dhamaal)",
                "Hook Up Song (Student of the Year 2)",
                "O Saki Saki (Batla House)",
                "Sheher Ki Ladki (Khandaani Shafakhana)",
                "Psycho Saiyaan (Saaho)",
                "Dheeme Dheeme (Pati Patni Aur Woh)",
                "Muqabla (Street Dancer 3D)",
                "Lagdi Lahore Di (Street Dancer 3D)",
                "Happy - Pharrell Williams",
                "Uptown Funk - Mark Ronson ft. Bruno Mars",
                "Can't Stop the Feeling! - Justin Timberlake",
                "Shake It Off - Taylor Swift",
                "I Gotta Feeling - The Black Eyed Peas",
                "All Star - Smash Mouth",
                "Hey Ya! - OutKast",
                "I Wanna Dance with Somebody",
                "Footloose - Kenny Loggins",
                "Party Rock Anthem - LMFAO",
                "Wannabe - Spice Girls",
                "Dancing Queen - ABBA",
                "Shut Up and Dance - Walk the Moon",
                "Twist and Shout - The Beatles",
                "Don't Stop Believin' - Journey",
                "Dynamite - BTS",
                "Firework - Katy Perry",
                "Shape of You - Ed Sheeran",
                "Walking on Sunshine - Katrina and the Waves",
                "September - Earth, Wind & Fire",
                "Wake Me Up - Avicii",
                "I Will Survive - Gloria Gaynor",
                "Sweet Caroline - Neil Diamond",
                "Happy Together - The Turtles",
                "Best Day of My Life - American Authors",
                "Good Vibrations - The Beach Boys",
                "I'm a Believer - The Monkees",
                "Girls Just Wanna Have Fun - Cyndi Lauper",
                "Hips Don't Lie - Shakira",
                "It's Raining Men - The Weather Girls",
                "Jump - Van Halen",
                "Shut Up and Drive - Rihanna",
                "The Way You Make Me Feel - Michael Jackson",
                "Can't Hurry Love - The Supremes",
                "I Love It - Icona Pop ft. Charli XCX",
                "Hey Soul Sister - Train",
                "Get Lucky - Daft Punk ft. Pharrell Williams",
                "Sweet Child o' Mine - Guns N' Roses",
                "Hey Jude - The Beatles",
                "Sweet Home Alabama - Lynyrd Skynyrd",
                "Livin' on a Prayer - Bon Jovi",
                "I'm Yours - Jason Mraz",
                "I Want to Hold Your Hand - The Beatles",
                "24K Magic - Bruno Mars",
                "Hymn for the Weekend - Coldplay",
                "Can't Take My Eyes Off You - Frankie Valli",
                "Footloose - Kenny Loggins",
                "Jump Around - House of Pain",
                "Shape of You - Ed Sheeran",
                "Let's Get Loud - Jennifer Lopez"
            ]
            list = random.sample(complete_list, 30)
            return list
